services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=controle_atendimento
      - MYSQL_ROOT_PASSWORD=34418502
      - MYSQL_PASSWORD=34418502
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=34418502"]
      interval: 3s
      timeout: 3s
      retries: 5

  api-rocket:
    build:
      context: .
    ports:
      - 3001:3000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    networks:
      - app

networks:
  app:
    driver: bridge
