version: "3"

services:
  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=controle_atendimento
      - MYSQL_ROOT_PASSWORD=34418502
      - MYSQL_PASSWORD=34418502
    networks:
      - app

  api-rocket:
    build:
      context: .
    ports:
      - 3001:3000
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    networks:
      - app

networks:
    app:
        driver: bridge