version: "3"

services:
  mysql:
    image: mysql:8
    ports:
      - 3000:3000
    environment:
      - MYSQL_DATABASE=controle_atendimento
      - MYSQL_ROOT_PASSWORD=34418502
      - MYSQL_PASSWORD=34418502

  api-rocket:
    build:
      context: .
    ports:
      - 3001:3000